[package]
name = "rsh"
version = "0.2.0"
edition = "2024"

[dependencies]
nix = {version = "0.31.1", features = ["process", "dir", "user", "hostname", "fs"]}
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
termion = "4.0.6"
