[package]
name = "rsh"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = {version = "0.31.1", features = ["process", "dir", "user", "hostname"]}
serde = "1.0.228"
serde_json = "1.0.149"
termion = "4.0.6"
